package com.wok.supportbot.config;

import com.wok.supportbot.repository.ProductRepository;
import com.wok.supportbot.service.ProductService;
import lombok.extern.slf4j.Slf4j;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.CommandLineRunner;
import org.springframework.boot.autoconfigure.condition.ConditionalOnProperty;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.ComponentScan;
import org.springframework.context.annotation.Configuration;
import org.springframework.jdbc.core.JdbcTemplate;
import org.mybatis.spring.annotation.MapperScan;

import javax.sql.DataSource;
import java.io.File;

/**
 * 数据库 + MyBatis Plus 配置
 * 仅在 rag.enabled=true 时激活
 * 重新扫描被排除的数据库相关包
 * 
 * 默认使用 H2 文件数据库（PostgreSQL 兼容模式），数据持久化到磁盘
 */
@Slf4j
@Configuration
@ConditionalOnProperty(prefix = "rag", name = "enabled", havingValue = "true")
@MapperScan({"com.wok.supportbot.dao", "com.wok.supportbot.repository"})
@ComponentScan(
        basePackages = {
                "com.wok.supportbot.repository",
                "com.wok.supportbot.dao",
                "com.wok.supportbot.service",
                "com.wok.supportbot.chatmemory"
        }
)
public class DatabaseConfig {

    @Autowired
    private DataSource dataSource;

    @Bean
    public JdbcTemplate jdbcTemplate() {
        return new JdbcTemplate(dataSource);
    }

    @Bean
    public ProductService productService(ProductRepository productRepository) {
        return new ProductService(productRepository);
    }

    /**
     * 初始化数据库表结构和初始数据
     */
    @Bean
    public CommandLineRunner initData(JdbcTemplate jdbcTemplate) {
        return args -> {
            File dataDir = new File("./data");
            if (!dataDir.exists()) {
                dataDir.mkdirs();
                log.info("创建数据目录: {}", dataDir.getAbsolutePath());
            }

            log.info("开始初始化数据库...");

            // ====== 1. sys_user 表 + 列升级 ======
            exe(jdbcTemplate,
                "CREATE TABLE IF NOT EXISTS sys_user (" +
                " id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY," +
                " org_id BIGINT DEFAULT 0 NOT NULL," +
                " username VARCHAR(50) NOT NULL UNIQUE," +
                " password VARCHAR(255) NOT NULL," +
                " nickname VARCHAR(100)," +
                " email VARCHAR(100)," +
                " phone VARCHAR(20)," +
                " role VARCHAR(20) DEFAULT 'ADMIN' NOT NULL," +
                " status VARCHAR(20) DEFAULT 'ACTIVE' NOT NULL," +
                " last_login_time TIMESTAMP," +
                " create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL," +
                " update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL," +
                " is_delete BOOLEAN DEFAULT FALSE NOT NULL" +
                ")");

            // ====== 2. 知识库/文档/RAG 表 ======
            exe(jdbcTemplate,
                "CREATE TABLE IF NOT EXISTS knowledge_base (" +
                " id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY," +
                " name VARCHAR(200) NOT NULL," +
                " description TEXT," +
                " icon VARCHAR(100)," +
                " status VARCHAR(20) DEFAULT 'ACTIVE' NOT NULL," +
                " document_count INTEGER DEFAULT 0 NOT NULL," +
                " org_id BIGINT DEFAULT 0 NOT NULL," +
                " create_by BIGINT," +
                " create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL," +
                " update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL," +
                " is_delete BOOLEAN DEFAULT FALSE NOT NULL" +
                ")");

            exe(jdbcTemplate,
                "CREATE TABLE IF NOT EXISTS document_category (" +
                " id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY," +
                " kb_id BIGINT NOT NULL," +
                " parent_id BIGINT DEFAULT 0 NOT NULL," +
                " name VARCHAR(200) NOT NULL," +
                " sort_order INTEGER DEFAULT 0 NOT NULL," +
                " create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL," +
                " update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL," +
                " is_delete BOOLEAN DEFAULT FALSE NOT NULL" +
                ")");

            exe(jdbcTemplate,
                "CREATE TABLE IF NOT EXISTS document (" +
                " id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY," +
                " kb_id BIGINT NOT NULL," +
                " category_id BIGINT," +
                " title VARCHAR(500) NOT NULL," +
                " content TEXT," +
                " file_type VARCHAR(50)," +
                " file_size BIGINT," +
                " file_path VARCHAR(500)," +
                " vector_status VARCHAR(20) DEFAULT 'PENDING' NOT NULL," +
                " quality_score DECIMAL(5,2)," +
                " version INTEGER DEFAULT 1 NOT NULL," +
                " org_id BIGINT DEFAULT 0 NOT NULL," +
                " create_by BIGINT," +
                " create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL," +
                " update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL," +
                " is_delete BOOLEAN DEFAULT FALSE NOT NULL" +
                ")");

            exe(jdbcTemplate,
                "CREATE TABLE IF NOT EXISTS document_version (" +
                " id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY," +
                " document_id BIGINT NOT NULL," +
                " version INTEGER NOT NULL," +
                " content TEXT," +
                " file_path VARCHAR(500)," +
                " change_summary VARCHAR(500)," +
                " create_by BIGINT," +
                " create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL," +
                " is_delete BOOLEAN DEFAULT FALSE NOT NULL" +
                ")");

            exe(jdbcTemplate,
                "CREATE TABLE IF NOT EXISTS kb_quality_check (" +
                " id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY," +
                " kb_id BIGINT NOT NULL," +
                " check_type VARCHAR(50) NOT NULL," +
                " check_result TEXT DEFAULT '{}'," +
                " score DECIMAL(5,2)," +
                " suggestions TEXT," +
                " check_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL," +
                " is_delete BOOLEAN DEFAULT FALSE NOT NULL" +
                ")");

            exe(jdbcTemplate,
                "CREATE TABLE IF NOT EXISTS chat_message (" +
                " id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY," +
                " conversation_id VARCHAR(64) NOT NULL," +
                " message_type VARCHAR(20) NOT NULL," +
                " content TEXT NOT NULL," +
                " metadata TEXT DEFAULT '{}'," +
                " create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL," +
                " update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL," +
                " is_delete BOOLEAN DEFAULT FALSE NOT NULL" +
                ")");

            exe(jdbcTemplate,
                "CREATE TABLE IF NOT EXISTS product (" +
                " id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY," +
                " name VARCHAR(200) NOT NULL," +
                " description TEXT NOT NULL," +
                " price DECIMAL(10, 2) NOT NULL," +
                " original_price DECIMAL(10, 2)," +
                " image_url VARCHAR(500)," +
                " category VARCHAR(100) NOT NULL," +
                " brand VARCHAR(100)," +
                " product_url VARCHAR(500)," +
                " sales_count INTEGER DEFAULT 0," +
                " status VARCHAR(20) DEFAULT 'ONLINE'," +
                " create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL," +
                " update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL," +
                " is_delete BOOLEAN DEFAULT FALSE NOT NULL" +
                ")");

            // ====== 4. 预置管理员账号 ======
            Integer userCount = jdbcTemplate.queryForObject("SELECT COUNT(*) FROM sys_user", Integer.class);
            if (userCount == null || userCount == 0) {
                jdbcTemplate.update(
                    "INSERT INTO sys_user (org_id, username, password, nickname, role, status) VALUES (?, ?, ?, ?, ?, ?)",
                    0L, "admin", "0192023a7bbd73250516f069df18b500", "平台超级管理员", "ADMIN", "ACTIVE"
                );
            }

            // ====== 5. 商品种子数据（幂等：id=1~15 不存在才插入） ======
            Object[][] products = {
                {1, "适老化扶手", "卫生间安全扶手，防滑防摔，适老化改造必备", 128.00, 198.00,
                    "https://example.com/images/handrail.jpg", "适老化改造", "苏福", "/pages/product/detail?id=1", 520, "ONLINE"},
                {2, "护理床", "家用多功能护理床，电动升降，医院级品质", 3580.00, 4800.00,
                    "https://example.com/images/bed.jpg", "康复护理", "苏福", "/pages/product/detail?id=2", 128, "ONLINE"},
                {3, "助行器", "轻便折叠助行器，老年人康复辅助器具", 268.00, 368.00,
                    "https://example.com/images/walker.jpg", "康复护理", "苏福", "/pages/product/detail?id=3", 356, "ONLINE"},
                {4, "智能手环", "健康监测智能手环，心率血氧监测，跌倒报警", 399.00, 599.00,
                    "https://example.com/images/bracelet.jpg", "智能穿戴", "苏福", "/pages/product/detail?id=4", 892, "ONLINE"},
                {5, "营养膳食套餐", "营养师定制养老膳食套餐，低盐低脂，营养均衡", 199.00, 299.00,
                    "https://example.com/images/meal.jpg", "健康餐饮", "苏福", "/pages/product/detail?id=5", 1250, "ONLINE"},
                {6, "上门按摩服务", "专业按摩师上门服务，缓解肩颈腰背疲劳", 198.00, 298.00,
                    "https://example.com/images/massage.jpg", "健康服务", "苏福", "/pages/product/detail?id=6", 234, "ONLINE"},
                {7, "康复理疗仪", "家用康复理疗仪，缓解肌肉酸痛，促进血液循环", 598.00, 898.00,
                    "https://example.com/images/therapy.jpg", "康复护理", "苏福", "/pages/product/detail?id=7", 445, "ONLINE"},
                {8, "适老化马桶", "智能适老化马桶，一键冲水，安全舒适", 2880.00, 3580.00,
                    "https://example.com/images/toilet.jpg", "适老化改造", "苏福", "/pages/product/detail?id=8", 89, "ONLINE"},
                {9, "老年大学课程", "线上老年大学课程，书法、绘画、太极等", 99.00, 199.00,
                    "https://example.com/images/class.jpg", "教育培训", "苏福", "/pages/product/detail?id=9", 2100, "ONLINE"},
                {10, "银发旅游", "专为老年人设计的康养旅游，全程医护陪护", 2980.00, 3980.00,
                    "https://example.com/images/travel.jpg", "旅游出行", "苏福乐游", "/pages/product/detail?id=10", 156, "ONLINE"},
                {11, "居家养老服务", "专业护理员上门，提供生活照料、康复护理", 199.00, 299.00,
                    "https://example.com/images/care.jpg", "养老服务", "苏福惠", "/pages/product/detail?id=11", 567, "ONLINE"},
                {12, "适老化改造套餐", "全屋适老化改造套餐，地面、扶手、灯光等", 9800.00, 12800.00,
                    "https://example.com/images/renovation.jpg", "适老化改造", "苏福", "/pages/product/detail?id=12", 45, "ONLINE"},
                {13, "助听器", "数字助听器，高清音质，适合老年人使用", 1980.00, 2980.00,
                    "https://example.com/images/hearing.jpg", "康复护理", "苏福", "/pages/product/detail?id=13", 234, "ONLINE"},
                {14, "血糖仪", "家用血糖仪，智能传输数据，异常预警", 268.00, 398.00,
                    "https://example.com/images/glucose.jpg", "健康监测", "苏福", "/pages/product/detail?id=14", 678, "ONLINE"},
                {15, "电动轮椅", "智能电动轮椅，轻便折叠，长续航", 3980.00, 5280.00,
                    "https://example.com/images/wheelchair.jpg", "康复护理", "苏福", "/pages/product/detail?id=15", 178, "ONLINE"},
            };
            for (Object[] p : products) {
                Integer exist = jdbcTemplate.queryForObject(
                        "SELECT COUNT(*) FROM product WHERE id = ?", Integer.class, p[0]);
                if (exist == null || exist == 0) {
                    jdbcTemplate.update(
                        "INSERT INTO product (id, name, description, price, original_price, image_url, category, brand, product_url, sales_count, status) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)",
                        p[0], p[1], p[2], p[3], p[4], p[5], p[6], p[7], p[8], p[9], p[10]
                    );
                }
            }
        };
    }

    private static void exe(JdbcTemplate jt, String sql) {
        jt.execute(sql);
    }
}
