-- H2 数据库初始化脚本
-- 创建所有业务表结构

-- 用户表
CREATE TABLE IF NOT EXISTS sys_user (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username        VARCHAR(50) NOT NULL UNIQUE,
    password        VARCHAR(255) NOT NULL,
    nickname        VARCHAR(100),
    email           VARCHAR(100),
    phone           VARCHAR(20),
    role            VARCHAR(20) DEFAULT 'ADMIN' NOT NULL,
    status          VARCHAR(20) DEFAULT 'ACTIVE' NOT NULL,
    last_login_time TIMESTAMP,
    create_time     TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    update_time     TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    is_delete       BOOLEAN DEFAULT FALSE NOT NULL
);

-- 知识库表
CREATE TABLE IF NOT EXISTS knowledge_base (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            VARCHAR(200) NOT NULL,
    description     TEXT,
    icon            VARCHAR(100),
    status          VARCHAR(20) DEFAULT 'ACTIVE' NOT NULL,
    document_count  INTEGER DEFAULT 0 NOT NULL,
    create_by       BIGINT,
    create_time     TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    update_time     TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    is_delete       BOOLEAN DEFAULT FALSE NOT NULL
);

-- 文档分类表
CREATE TABLE IF NOT EXISTS document_category (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kb_id           BIGINT NOT NULL,
    parent_id       BIGINT DEFAULT 0 NOT NULL,
    name            VARCHAR(200) NOT NULL,
    sort_order      INTEGER DEFAULT 0 NOT NULL,
    create_time     TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    update_time     TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    is_delete       BOOLEAN DEFAULT FALSE NOT NULL
);

-- 文档表
CREATE TABLE IF NOT EXISTS document (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kb_id           BIGINT NOT NULL,
    category_id     BIGINT,
    title           VARCHAR(500) NOT NULL,
    content         TEXT,
    file_type       VARCHAR(50),
    file_size       BIGINT,
    file_path       VARCHAR(500),
    vector_status   VARCHAR(20) DEFAULT 'PENDING' NOT NULL,
    quality_score   DECIMAL(5,2),
    version         INTEGER DEFAULT 1 NOT NULL,
    create_by       BIGINT,
    create_time     TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    update_time     TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    is_delete       BOOLEAN DEFAULT FALSE NOT NULL
);

-- 文档版本历史表
CREATE TABLE IF NOT EXISTS document_version (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_id     BIGINT NOT NULL,
    version         INTEGER NOT NULL,
    content         TEXT,
    file_path       VARCHAR(500),
    change_summary  VARCHAR(500),
    create_by       BIGINT,
    create_time     TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    is_delete       BOOLEAN DEFAULT FALSE NOT NULL
);

-- 知识库质量检测表
CREATE TABLE IF NOT EXISTS kb_quality_check (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kb_id           BIGINT NOT NULL,
    check_type      VARCHAR(50) NOT NULL,
    check_result    TEXT DEFAULT '{}',
    score           DECIMAL(5,2),
    suggestions     TEXT,
    check_time      TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    is_delete       BOOLEAN DEFAULT FALSE NOT NULL
);

-- 聊天消息表
CREATE TABLE IF NOT EXISTS chat_message (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    conversation_id VARCHAR(64) NOT NULL,
    message_type    VARCHAR(20) NOT NULL,
    content         TEXT NOT NULL,
    metadata        TEXT DEFAULT '{}',
    create_time     TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    update_time     TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    is_delete       BOOLEAN DEFAULT FALSE NOT NULL
);

-- 商品表
CREATE TABLE IF NOT EXISTS product (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            VARCHAR(200) NOT NULL,
    description     TEXT NOT NULL,
    price           DECIMAL(10, 2) NOT NULL,
    original_price  DECIMAL(10, 2),
    image_url       VARCHAR(500),
    category        VARCHAR(100) NOT NULL,
    brand           VARCHAR(100),
    product_url     VARCHAR(500),
    sales_count     INTEGER DEFAULT 0,
    status          VARCHAR(20) DEFAULT 'ONLINE',
    create_time     TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    update_time     TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    is_delete       BOOLEAN DEFAULT FALSE NOT NULL
);

-- 注：初始数据由 DatabaseConfig.java 中的 CommandLineRunner 初始化